services:
  tests-db:
    image: postgres:16
    container_name: metadata-test-db
    restart: unless-stopped
    env_file: .env.tests
    ports:
      - "55432:5432"
    volumes:
      - ../schema/initial.sql:/docker-entrypoint-initdb.d/initial.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 6
